%YAML 1.2
%TAG !n! tag:nimyaml.org,2016:
--- !n!custom:MonitorConfig 
sleep: 1
targets: 
  - 
    name: Test
    paths: [src, tests]
    commands: [nimble test]
    extensions: [.nim]
    files: []
    exclude_extensions: []
    exclude_files: []
    once: y
